-- One-line CREATE so migration runners that split on ";" cannot break the statement.
-- Runs before 20260127100000 (legacy ALTER ADD VALUE).

CREATE TYPE "NotificationType" AS ENUM ('PR_DEPARTMENT_HEAD_APPROVED', 'PR_BRANCH_MANAGER_APPROVED', 'PR_RETURNED', 'PR_OVER_BUDGET', 'PR_PENDING_APPROVAL', 'PR_RETURNED_FROM_BRANCH', 'PR_OVER_BUDGET_INFO', 'PR_READY_FOR_ASSIGNMENT', 'PR_QUOTATIONS_COMPLETE', 'PR_OVER_BUDGET_ACTION_REQUIRED', 'PR_RETURNED_FROM_BRANCH_MANAGER', 'RFQ_SUBMITTED', 'PR_ASSIGNED', 'PR_RETURNED_FOR_REQUOTE', 'RFQ_REQUIRED', 'PR_PENDING_APPROVAL_BRANCH', 'PR_OVER_BUDGET_DECISION_REQUIRED');
