-- Add new PRStatus values introduced after initial enum
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'DEPARTMENT_HEAD_PENDING';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'DEPARTMENT_HEAD_APPROVED';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'DEPARTMENT_HEAD_REJECTED';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'DEPARTMENT_HEAD_RETURNED';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'MANAGER_PENDING';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'MANAGER_APPROVED';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'MANAGER_REJECTED';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'MANAGER_RETURNED';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'BRANCH_MANAGER_PENDING';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'BRANCH_MANAGER_APPROVED';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'BRANCH_MANAGER_REJECTED';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'BRANCH_MANAGER_RETURNED';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'BUYER_LEADER_PENDING';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'ASSIGNED_TO_BUYER';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'BUDGET_EXCEPTION';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'BUDGET_APPROVED';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'BUDGET_REJECTED';


