-- Add new PRStatus values for manager approval and buyer leader queue
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'MANAGER_PENDING';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'MANAGER_APPROVED';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'MANAGER_REJECTED';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'MANAGER_RETURNED';
ALTER TYPE "PRStatus" ADD VALUE IF NOT EXISTS 'BUYER_LEADER_PENDING';


